#+OPTIONS: toc:nil
#+LATEX_HEADER: \usepackage{parskip}

An extensible parameterized decision support system for bridge maintenance.

**Extensibility** is a software engineering and systems design principle that
provides for future growth. Extensibility is a measure of the ability to extend
a system and the level of effort required to implement the extension.

A **decision support system for bridge maintenance** is a software system that
provides the user of the system with information on the state of a bridge. This
information can allow the user of the system to make a more informed decision
about when maintenance should be carried out. The information that is provided
to the user can include real-time sensor data and an analysis thereof.

In the development of a decision support system it is **necessary to have sensor
data** corresponding to both the damaged and undamaged states of the bridge in
question. Due to the expensive nature of a bridge it is usually not allowed to
impose a damaged state on the bridge. The use of finite element software allows
for the generation of simulated sensor data via a finite element model of a
bridge on which different damage states can be imposed.

A finite element model is a model of a structure in software. All models are
wrong and thus the simulated sensor data generated by the finite element model
will **differ from sensor data collected from real installed sensors**. The
simulated sensor data should be close enough to reality to provide confidence
that the developed anaysis techniques can also work with real sensor data, while
acknowleding that additional work would be needed to tune the anaysis techniques
once real sensor data is available.

For a software system to be extensible, the source code must be available to any
user wishing to extend said software. The benefits of **open source software**
are well known, in particular open source software allows /any individual with
an interest/ to develop or /extend/ the software. Open source software can thus
leverage the knowledge of the community and prevent duplication of efforts which
can occur when software is developed behind closed doors. Open source software
also provides transparency to anyone wishing to investigate the software and may
produce more reliable software due to more people having eyes on it.

**OpenSees** (The Open System for Earthquake Engineering Simulation) is an open
source finite element software framework that anyone with a Windows, macOS or
Linux machine, and an internet connection, can download and install. Depending
on open source finite element software enables users to explore or extend the
decision support software without requiring an expensive proprietary licence. In
contrast to the Diana finite element software package, also used in this thesis,
OpenSees does not require a licence for use and is additionaly available for
macOS users.

A finite element simulation of a bridge will produce sensor data that is
necessarily different from data collected from real installed sensors. It is
necessary to **validate the simulated data against some ground truth** in order
to have some confidence in the accuracy of the simulated data, and it is also
desirable to **test the developed analysis techniques on real data** such that
we have some confidence in these techniques.

In this thesis we focus on bridge 705 in Amsterdam for which a verified 3D
finite element model for Diana is available. This allows us to address the point
on **validation** by comparing the sensor data collected by simulation with
OpenSees to data from simulation by Diana. In order for the developed decision
support system to be truly extensible it is not limited to depend on a single
finite element program. The system has as a parameter a method of communication
with a finite element program, such that data can be collected and analyzed from
different finite element programs, in this case OpenSees and Diana.

The analysis techniques in this thesis aim to distinguish between data in two
states, a normal or healthy state, and an abnormal or damaged state. While we do
not have availabe bridge data from a normal and abnormal state we do have 15
years of data from viaducts for which there are two states available, high and
low temperature. In this thesis the **developed analysis techniques are tested**
on this data to provide, an albeit limited, test that the techniques can perform
a classification between states.

The developed decision support system has a number of **parameters** such that
users wishing to extend the software further are not limited to focus on bridge
705 or to use a specific finite element program. The specification of a bridge
is a parameter of the system, as is the type and intensity of traffic on the
bridge. Furthermore, as mentioned earlier, different finite element programs can
be integrated with this system, which may be useful if a finite element model of
a bridge for a different finite element program is already available to the
user.
