#+AUTHOR: Jeremy Barisch-Rooney
#+TITLE: How sensors can be utilized to build a decision support system for bridge maintenance
#+LATEX_HEADER: \usepackage{parskip}

* Introduction
   # Introduction of the research question/title.
   The probability of a bridge to fail increases over time until it is no longer
   considered safe for use. Maintenance of a bridge is typically carried out
   when something goes wrong or according to a preventative maintenance schedule
   based on expert knowledge, neither approach making the best use of limited
   maintenance resources. Sensors can provide useful real-time information
   without the delay or cost of a manual maintenance check. How sensors can be
   utilized to build a decision support system for bridge maintenance is the
   topic of this thesis.

   # Sensors and why bridge 705.
   Sensors on bridges can provide real-time measurements of the responses of the
   part of the bridge on which they are installed. Depending on the sensor-type
   this measured response may be translation, rotation, vibration or one of many
   other types of response. In this thesis the focus is on a single bridge,
   bridge 705 in Amsterdam. The reason bridge 705 was chosen is because a 3D
   finite element model (FEM) is available for the bridge, and a field test was
   conducted where known loads were applied to the bridge and the corresponding
   sensor measurements recorded. The FEM is useful so that sensor measurements
   for a known load can be simulated without having to conduct a field test, the
   measurements from the field test allow us to verify this data generated by
   simulation.

   # A decision support system.
   A decision support system for bridge maintenance must provide information on
   the damage status of the bridge to the user of the system or policy maker.
   Thus it is necessary to transform the responses measured by the sensors into
   a damage report of the bridge. To accomplish this a model will be built that
   generates a damage report based on two methods which will be referred to from
   now on as abnormal condition classification (ACC) and similar structure
   similar behaviour (SSSB).

   # ACC.
   The goal of ACC is to determine if the condition of the bridge has deviated
   from the normal range of conditions. To build an ACC system it is necessary
   to first find out what the range of sensor measurements are during normal
   operation of the bridge. This will be achieved by applying a normal range of
   loading conditions to the FEM and recording the simulated sensor
   measurements. Then a one-class classifier can be applied to the simulated
   responses and be used to decide if any subsequent sensor measurements fall
   within the expected normal range of responses or not.

   # SSSB.
   The SSSB method is based on the assumption that similar structures should
   behave in a similar manner when subjected to the same load. Bridge 705 in
   Amsterdam has seven spans each with the same dimensions, ignoring the small
   differences due to construction and time in operation. To develop an SSSB
   system loads must be "driven" across the bridge in the FEM, then an analysis
   must be performed on the difference between sensor measurements from sensors
   at equivalent positions on each substructure.
   
   # End goal.
   The end-goal of this thesis is to outline how sensors can be utilized to
   build a decision support system for bridge maintenance. To accomplish this a
   model will be built (consisting of the AAC and SSSB methods) to determine if
   sensor measurements represent an abnormal condition of the bridge . Research
   will be conducted to ascertain what types of sensors and what sensor
   placement is optimal for detecting such an abnormal condition. A finite
   element model will be used to simulate sensor measurements in order to
   address the lack of available data. Due to the safety requirements of any
   bridge it is necessary to quantify the uncertainty we have in our damage
   estimates. Once the capabilities and limitations of the model are understood,
   we will suggest a decision support system for policy makers which includes
   the model and present a cost-benefit analysis thereof. Finally (stretch-goal)
   we will investigate how such a system can be generalized to bridges other
   than bridge 705.
   
   # Structure of this thesis.
* Literature review
  This section contains a review of relevant literature studied during this
  thesis project.
** Combining Data-driven Methods with Finite Element Analysis for Flood Early Warning Systems
** Neural Clouds for Monitoring of Complex Systems
   # One-class classification.
   In one-class classification, a classifier attempts to identify objects of a
   single class among all objects by learning from a training set that consists
   only of objects of that class. One-class classifiers are useful in the domain
   of system condition monitoring because often only data corresponding to the
   normal range of operating conditions is available. Data corresponding to the
   class of abnormal conditions, when a failure or breakdown of a system has
   occurred, is often not available or is difficult or expensive to obtain.

   # Neural Clouds algorithm.
   The Neural Clouds (NC) method presented in TODO:REF is a one-class classifier
   which provides a confidence measure of the condition of a complex system. In
   the NC algorithm we are dealing with measurements from a real object where
   each measurement is considered as a point in n-dimensional space. First a
   normalization procedure is applied to the data to avoid clustering problems
   in the subsequent step. The data is then clustered and the centroids of the
   clusters extracted. The centroids are then encapsulated with "Gaussian
   bells", and these Gaussian bells are normalized to avoid outliers in the
   data. The summation of the Gaussian bells results in a height =h= for each
   point =p= on the hyperplane of parameter values. The value of =h= at a point
   =p= can be interpreted as the probability of the parameter values at =p=
   falling within the normal conditions represented by the training data. In
   comparison to other one-class classifiers, the NC method has an advantage in
   condition monitoring in that it creates this unique plateau where height can
   be interpreted as probability of the system condition. Figure TODO:FIG shows
   this plateau in comparison with other one-class classifiers.
** Similar Substructures on Sydney Harbour Bridge
   # SSSB method on SHB. 
