#+OPTIONS: toc:nil

* Slide 1
  Hi, my name is Jeremy Barisch-Rooney. I am from Ireland, half German. I did an
  undergraduate degree in software engineering and I work in the same field.

  I’m doing a Master degree in Computational Science at the University of
  Amsterdam and for my thesis I’m working on a project that is a joint
  collaboration between the UoA’s IAS department and TNO.

  I will start working on my thesis full time in June, so far I have just been
  using some of the days I have available to me on this thesis.

  The working title of my research is “how can sensors be used in a data-driven
  decision support system for bridges”.
* Slide 2 
  My supervisors here are Arpad and Arthur and representing the interests of the
  University of Amsterdam is Valeria from the IAS department, who is doing work
  in Policy by simulation, which they define as “developing computational models
  that help to predict the effect of policy measures, technology development and
  new business models in several domains such as energy transition, cities and
  mobility, crime and public health.

  Some of Valeria’s work related to the monitoring of levees and dikes, part of
  this research included an early warning and decision support system based on
  sensor data.

  For my thesis the research will have some parallels to Valeria’s work, but
  instead of levees and dikes I am looking at bridges.
* Slide 3
  Maintenance of assets can be done when the damage occurs, meaning assets
  operate at reduced service levels until resources are mobilised to repair the
  problem.

  Preventative maintenance is an improvement though often inefficient as
  maintenance may be done too early or too late.

  We hope that sensor data provides enough information to provide a useful
  decision support system for bridges to make better use of maintenance
  resources.
* Slide 4
  The potential value of sensor-based monitoring includes:

  Detecting an incident as early as possible.
  
  Enable condition-based maintenance, providing information on which parts of a
  structure are damaged.

  Sensors are always collecting more data which can be used to improve the
  system.

  Together this allows for decision makers to make the best use of limited
  maintenance resources via a decision support system. 
* Slide 5 
  Whereas Xuzheng's work is on determining specific hidden parameters of the
  structure, this work attempts first to achieve damage detection or an abnormal
  state, and then where possible identify which substructure contains the
  abnormal state and what type of abnormal state. Naturally the more information
  we can make available in the decision support system the better for the
  decision maker.
* Slide 6
  Initial focus is on bridge 705 in Amsterdam.

  The reason this bridge was chosen is that we have available sensor
  measurements from an experiement where bridge 705 was loaded with known loads,
  thus we know the loads that correspond to the given sensor measurements.
  
  We also have a 3D FE model which can be used to simulate the condition of the
  bridge under different loads, allowing us to create fake or synthetic data.
  
  The sensor measurements can then be used to verify the accuracy of the
  synthetic data.
* Slide 8
  I want to classify the bridge state as under normal condition or abnormal.
  However we only have sensor measurements corresponding to normal conditions,
  and only a very limited set of normal conditions. For obvious reasons we don't
  have sensor data corresponding to damage to the bridge.
  
  In cases where only data corresponding to one class is available we can still
  do classification. These are called one class classifiers and in the case of
  bridge 705 the class is "normal operating conditions".
  
  What I will do is use the available sensor measurements to verify the
  synthetic data generated by the FE model. The synthetic data generated by the
  FE model will correspond to normal operating conditions, normal loads applied
  to the bridge.
* Slide 9
  Once we have the synthetic data representing normal operating conditions we
  can project this data to a "cloud" in n-dimensional space. Any testing data
  can be projected in a similar manner to see if it falls within the cloud, and
  is then classified as a normal operating condition, or outside the cloud, and
  classified as an abnormal operating condition.
* Slide 10
  Here is an example of a neural cloud in comparison to two other "one class"
  classifiers. In contrast to the other two approaches you can see how a sort of
  protective barrier or "cloud" surrounds the data points. In the other two
  cases you could have a data point which is similar to the data representing
  your "normal" class but which is still classified as abnormal.
* Slide 11
  Similar substructures should behave the same way when subjected to the same
  load. So when a truck is driving over the bridge we would expect the same
  response from different sensors.

  Bridge 705 has 7 spans. If there is structural damage at one point in the
  bridge then we would expect the sensors to behave differently as the truck
  passes over each span.

  This is a part of the project I'm particularly interested in looking at. This
  idea comes from the Sydney Harbour Bridge which has 800 jack arches under
  traffic lane 7 and a similar monitoring system was developed, which
  succesfully detected three jack arches with issues.
  
  The primary difficulty in the case of bridge 705 is determining the response
  of the sensors we would expect as traffic passes over the bridge, for example
  consider one truck moving across the bridge. We would expect a similar
  response over the next span with a short time delay, this is the relatively
  simple case. Now what about two trucks moving in opposite directions, and now
  what about heavy traffic?
* Slide 12
  Now I'm going to outline the approach that this thesis will follow.

  The approach can be split into four main parts, the generation of synthetic
  data, determining optimal sensor placement, creating a data-driven model to
  infer damage status of the bridge, and then finally the decision support
  support system of which everything above is a part of.
* Slide 13
  To generate synthetic data corresponding to normal operating conditions the
  first part is to determine what normal operating conditions are. What is the
  distribution of load on the bridge, at a single point in time, and how does
  the load change over time? If anyone has knowledge regarding load/traffic
  patterns please come find me after the talk, this is valuable data for the
  project.

  Once the normal operating conditions are determined it is necessary to
  generate the synthetic data from a FE model, this means applying the normal
  operating loads in a FE model, and measuring the response which we would
  expect from different kinds of sensors, translation and strain in particular.
  
  From the experiments performed on bridge 705 then the synthethic data
  generated can be verified against sensor measurements.
* Slide 14
  Xuzheng has done a lot of work relating to sensor placement. In my case the
  definition of optimal will dictate the optimal sensor placement strongly. In
  particular the cost of sensors must be included in the evaluation term.

  How many sensors of different types should be placed on the structure to
  minimise our evaluation function, which will have cost and explanatory
  information terms.

  This is a general optimisation problem, to constrain the problem space it is
  likely desirable to place sensors in the same position on each similar
  substructure.
* Slide 15
  Determing damage or abnormal conditions is clearly a central part of this
  project.

  Using the synthetic data which related loads to sensor responses it should be
  possible to determine abnormal conditions with some data-driven driven
  approach such as the neural cloud or similar substructures techniques.
  
  In Valeria's work related to levees a combination of data-driven and FE model
  techniques were used to determine abnormal conditions. Here's a diagram
  showing how the data is used both for detection but also for continual
  training of the system.
* Slide 17
  Finally this entire system would ideally be used as part of a decision support
  system so the data can be used to allow decision makers make better use of
  limited maintenance resources.

  I will outline such a system, similar to what has been presented on the
  previous slide. At a high-level such a system consists of three parts, data
  acquisition, data analysis, and decision support interface which presents the
  results of the analysis.
  
  Of particular interest here is a cost-benefit analysis of such a system,
  showing the feasibility of the system to be used in real. Costs include
  installation, power, networking, data processing and much more.
* Slide 18
  It would be nice to show what is necessary to generalise such a system to
  other bridges, but there is already a low of work involved so I don't foresee
  much if anything being done here.
* Slide 19
  Here is an overview of the deliverables I want to see by the end of the
  project, it is really a summary of the previous slides. We have...
* Slide 20
  ...
